export const EVENTS = {
	connection: "connection",
	CLIENT: {
		CREATE_ROOM: "CREATE_ROOM",
		JOIN_ROOM: "JOIN_ROOM",
		LEAVE_ROOM: "LEAVE_ROOM",
	},
	SERVER: {
		ROOMS: "ROOMS",
		JOINED_ROOM: "JOINED_ROOM",
		PLAYER_JOIN_CLIENT_ROOM: "PLAYER_JOIN_CLIENT_ROOM",
	},
}
