export const EVENTS = {
	connection: "connection",
	CLIENT: {
		CREATE_ROOM: "CREATE_ROOM",
		JOIN_ROOM: "JOIN_ROOM",
		LEAVE_ROOM: "LEAVE_ROOM",
		REFRESH_ROOM: "REFRESH_ROOM",
		MOVE: "MOVE",
	},
	SERVER: {
		ROOMS: "ROOMS",
		JOINED_ROOM: "JOINED_ROOM",
		PLAYER_JOIN_CLIENT_ROOM: "PLAYER_JOIN_CLIENT_ROOM",
		UPDATE_GAME_DATA: "UPDATE_GAME_DATA",
	},
}
